baseURL = "https://chickenproject.org/"
languageCode = "en-us"
title = "The Chicken Project"
theme = "ananke"
SectionPagesMenu = "main"

[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  instagram = "https://www.instagram.com/lizamcconnell/"
  facebook = ""
  youtube = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-blue"
  featured_image = "https://ik.imagekit.io/4sfetty7t5p/IMG_2469_SesNU2cXg.JPG?tr=w-1200,h-675,fo-auto"
  recent_posts_number = 2
